---
- name: install nginx
  apt:
    name: nginx
    state: present
  when: apt

- name: deploy static
  copy:
    src: index.html
    dest: /var/www/html/index.html
    mode: '0644'
  notify:
    - restart
  when: apt


- name: install pip
  apt:
    name: python3-pip
    state: present
  when: docker

- name: pip install docker
  pip:
    name: docker
    state: present
  when: docker

- name: deploy nginx container
  docker_container:
    name: nginx
    image: "{{ image }}"
    state: started
    ports:
      - "80:80"
  when: docker